### PR TITLE
fix: tests on simulate experiment

### PR DESCRIPTION
**Pull request by ThibaultFy**
## Summary

Tests passed locally ✅

### CODE REVIEW

**Comment by guilhem-barthes** [comment]
Should we run the CI?

**Review by thbcmlowk — APPROVED** [review]
LGTM!

**Comment by ThibaultFy** [comment]
> Should we run the CI?

these tests are not run on CI e2e, but only with the local one (on which we can't specify branches). I ran them locally.

**Review by guilhem-barthes — APPROVED** [review]
📍

**Pull request merged**
