### PR TITLE
Fix: fix docker build 

### PR DESCRIPTION
**Pull request by SdgJlbl**
Fix following https://github.com/Substra/substrafl/pull/110

### CODE REVIEW

**Comment by SdgJlbl** [comment]
/e2e --tests sdk,frontend,substrafl --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by oleobal** [comment]
that was the flakey test failing

/e2e --tests sdk,substrafl --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by SdgJlbl** [comment]
https://github.com/owkin/substra-ci/actions/runs/4666377201

**Review by ThibaultFy — APPROVED** [review]
Test passed locally for me.
Thx for the quick fix

**Pull request merged**
