### PR TITLE
chore: remove warnings from pydantic v2

### PR DESCRIPTION
**Pull request by ThibaultFy**
## Related issue

closes FL-1241

- [ ] If the feature has an impact on the user experience, the [changelog](https://github.com/substra/substrafl/blob/main/CHANGELOG.md) has been updated
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] The commit message follows the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification

### CODE REVIEW

**Review by SdgJlbl — APPROVED** [review]
Thank you :)

**Comment by Owlfred** [comment]
```
Usage: /e2e [options] [help]

/e2e may appear anywhere as long as it is on its own line

Options:
  --refs <value>                          Extra refs (branch or tag) with format REPO=GIT_REF,REPO=GIT_REF.
  Supported repositories: orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, substra-documentation, substra-ci.
  Example: /e2e --refs substra-backend=some_branch,orchestrator=some_tag (default: {})
  --tests-to-run, --tests <tests-to-run>  Comma-separated list of tests to run. Valid options: sdk, substrafl, doc, frontend, mnist, camelyon or NONE. (default: "sdk")
  -h, --help                              display help for command
```

**Comment by ThibaultFy** [comment]
> I saw more `pydantic` warnings to be fixed in the CI logs. For instance:
> 
> ```
> substrafl/dependency/schemas.py:86
>   /usr/src/app/substrafl/substrafl/dependency/schemas.py:86: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
>     @validator("local_installable_dependencies", "local_code")
> ```
> 
> ```
>   /usr/local/lib/python3.11/site-packages/pydantic/_internal/_config.py:267: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
>     warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
> ```
> 
> It might be _[quote]_ << **worth** >> _[unquote]_ fixing them in this PR. WDYT?

Yep I tried to fix them too. It's linked to the fact we are overwritting the `__del__` function in Dependencies, and pydentic overwrite `__delattr__`on there side. These two + the pytest management on garbage collection seems to be 💥 . These logs does not appears to users with a "normal" usage of dependencies... I can continue to look at this though..

**Comment by thbcmlowk** [comment]
> > I saw more `pydantic` warnings to be fixed in the CI logs. For instance:
> > ```
> > substrafl/dependency/schemas.py:86
> >   /usr/src/app/substrafl/substrafl/dependency/schemas.py:86: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
> >     @validator("local_installable_dependencies", "local_code")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >   /usr/local/lib/python3.11/site-packages/pydantic/_internal/_config.py:267: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
> >     warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It might be _[quote]_ << **worth** >> _[unquote]_ fixing them in this PR. WDYT?
> 
> Yep I tried to fix them too. It's linked to the fact we are overwritting the `__del__` function in Dependencies, and pydentic overwrite `__delattr__`on there side. These two + the pytest management on garbage collection seems to be 💥 . These logs does not appears to users with a "normal" usage of dependencies... I can continue to look at this though..

No worries, not that big of deal. It was just in case it was an easy fix. Thanks for looking at it in the first place!

**Pull request merged**
