### PR TITLE
chore: add documentation and check on logger

### PR DESCRIPTION
**Pull request by ThibaultFy**
## Related issue

closes FL-1222

## Please check if the PR fulfills these requirements

- [ ] If the feature has an impact on the user experience, the [changelog](https://github.com/substra/substrafl/blob/main/CHANGELOG.md) has been updated
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] The commit message follows the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification

### CODE REVIEW

**Review by SdgJlbl — APPROVED** [review]
I still think that the library should not be the one setting the log level, and that it is of the responsibility of the end user, but this is better than nothing 👍

**Comment by ThibaultFy** [comment]
> I still think that the library should not be the one setting the log level, and that it is of the responsibility of the end user, but this is better than nothing 👍

In that case we could also change the way we print info for the user ?

**Comment by SdgJlbl** [comment]
> > I still think that the library should not be the one setting the log level, and that it is of the responsibility of the end user, but this is better than nothing 👍
> 
> In that case we could also change the way we print info for the user ?

From a semantic point of view, the log level INFO makes sense for the information we print. 

The issue is that new users might be unaware that some information could be displayed if they don't change the log level. Unless we highlight that in tutorials, maybe...?

**Comment by ThibaultFy** [comment]
> > > I still think that the library should not be the one setting the log level, and that it is of the responsibility of the end user, but this is better than nothing 👍
> > 
> > 
> > In that case we could also change the way we print info for the user ?
> 
> From a semantic point of view, the log level INFO makes sense for the information we print.
> 
> The issue is that new users might be unaware that some information could be displayed if they don't change the log level. Unless we highlight that in tutorials, maybe...?

Can be a good idea yes. Or in a normal library I guess someone will raise this issue on stackoverflow, we will answer, and then everyone would refer to this issue x)

**Pull request merged**
