### PR TITLE
chore: release 0.40.0

### PR DESCRIPTION
**Pull request by Milouu**
### Added

- Check the Python version used before generating the Dockerfile ([#155])(<https://github.com/Substra/substrafl/pull/155>)).
- Python dependencies can be resolved using pip compile during function registration by setting `compile` to `True`
  in the `Dependency` object ([#155])(<https://github.com/Substra/substrafl/pull/155>)).

  ```py
  Dependency(
        pypi_dependencies=["pytest", "numpy"],
        compile=True,
    )
  ```

- `Dependency` objects are now computed at initialization in a cache directory, accessible through the `copy_compute_dir` method. The cache directory is deleted at the `Dependency` object deletion. ([#155])(<https://github.com/Substra/substrafl/pull/155>))
- Check created wheels name. ([#160](https://github.com/Substra/substrafl/pull/160))

### Changed

- BREAKING: Rename `generate_wheel.py` to `manage_dependencies.py` ([#156](https://github.com/Substra/substrafl/pull/156))
- BREAKING: Move `manage_dependencies.py` from `remote.register` to `dependency` ([#158](https://github.com/Substra/substrafl/pull/158))
- BREAKING: `local_dependencies` is renamed `local_installable_dependencies` ([#158](https://github.com/Substra/substrafl/pull/158))
- BREAKING: local_installable_dependencies are now limited to local modules or Python wheels (no support for bdist, sdist...)([#155])(<https://github.com/Substra/substrafl/pull/155>)).

### Fixed

- Set, save & load `random.seed` and `np.random.seed` along with `torch.manual_seed` in `TorchAlgo`([#151](https://github.com/Substra/substrafl/pull/151))

### CODE REVIEW

**Review by SdgJlbl — APPROVED** [review]
Thanks

**Review by SdgJlbl — CHANGES_REQUESTED** [review]
I think there's an error in the changelog, checking

**Comment by SdgJlbl** [comment]
The `copy_compute_dir` method no longer exists, the cache directory is now directly accessible under `cache_directory`. 
I'd change the changelog as follow
```
- Dependency objects are now computed at initialization in a cache directory, accessible through the `cache_directory` attribute. The cache directory is deleted at the Dependency object deletion. ([https://github.com/Substra/substrafl/pull/155])(https://github.com/Substra/substrafl/pull/155))
```

**Comment by ThibaultFy** [comment]
@SdgJlbl good catch.. Sorry for that. Thanks a lot !

**Review by SdgJlbl — APPROVED** [review]
Thanks, sorry for the last minute change

**Comment by Milouu** [comment]
Done, thanks for the catch 😄

**Comment by SdgJlbl** [comment]
> @SdgJlbl good catch.. Sorry for that. Thanks a lot !

I missed it on my final review of your PR too 🙂

**Pull request merged**
