### PR TITLE
chore: use protocols for nodes

### PR DESCRIPTION
**Pull request by ThibaultFy**
## Related issue

Companion PR:
- https://github.com/Substra/substrafl/pull/185
- https://github.com/Substra/substra-documentation/pull/398

closes FL-1290

## Please check if the PR fulfills these requirements

- [ ] If the feature has an impact on the user experience, the [changelog](https://github.com/substra/substrafl/blob/main/CHANGELOG.md) has been updated
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] The commit message follows the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification

### CODE REVIEW

**Review by SdgJlbl — APPROVED** [review]
Thanks ❤️

**Comment by guilhem-barthes** [comment]
While we are at renaming nodes, what is the reason that made us call  `TrainDataNode` & `TestDataNode` and not `TrainNode` and `TestNode` ?

**Comment by ThibaultFy** [comment]
> While we are at renaming nodes, what is the reason that made us call `TrainDataNode` & `TestDataNode` and not `TrainNode` and `TestNode` ?

Is to emphasize  that these nodes are linked to datasamples. But I guess this is a valid question and both naming have there plus and cons...

**Comment by guilhem-barthes** [comment]
> > While we are at renaming nodes, what is the reason that made us call `TrainDataNode` & `TestDataNode` and not `TrainNode` and `TestNode` ?
> 
> Is to emphasize that these nodes are linked to datasamples. But I guess this is a valid question and both naming have there plus and cons...

Could we have Test or Train without data? but indeed that maybe a topic to take further out off this PR

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
```
Usage: /e2e [options] [help]

/e2e may appear anywhere as long as it is on its own line

Options:
  --refs <value>                          Extra refs (branch or tag) with format REPO=GIT_REF,REPO=GIT_REF.
  Supported repositories: orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, substra-documentation, substra-ci.
  Example: /e2e --refs substra-backend=some_branch,orchestrator=some_tag (default: {})
  --tests-to-run, --tests <tests-to-run>  Comma-separated list of tests to run. Valid options: sdk, substrafl, doc, frontend, mnist, camelyon or NONE. (default: "sdk")
  -h, --help                              display help for command
```

**Comment by ThibaultFy** [comment]
/e2e --refs substra-documentation=chore/rename-testnode --tests doc

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --refs substra-documentation=chore/rename-testnode --tests doc

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --refs substra-documentation=chore/rename-testnode --tests doc

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
