### PR TITLE
fix(benchmark): download data for camelyon

### PR DESCRIPTION
**Pull request by ThibaultFy**
## Related issue

closes FL-1250

## Comment

Zenodo changed the access management to some of there datasets (for instance to ensure that its access for academic purposes)
We changed our download url to point to a dataset we (owkin) put online -> https://zenodo.org/records/7053167

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by thbcmlowk — APPROVED** [review]
GG!

**Pull request merged**
