### PR TITLE
chore: unpin NumPy to allow use of 2.0

### PR DESCRIPTION
**Pull request by SdgJlbl**
End-to-end tests here https://github.com/Substra/substra-documentation/pull/441#issuecomment-2383038220

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
The pin was to prevent incompatibilities regarding pickle. What is the issue with it ?

**Comment by SdgJlbl** [comment]
> The pin was to prevent incompatibilities regarding pickle. What is the issue with it ?

Keeping a pin to an old version of NumPy is going to be more and more problematic down the line, as more recent versions of pandas / pytorch might not support NumPy 1.x. 

If it's working with NumPy 2.x, I think we should allow it. 

Do you remember when the issue with pickle was occurring?

**Review by guilhem-barthes — APPROVED** [review]

**Pull request merged**
