### PR TITLE
chore: add python 3.11 support

### PR DESCRIPTION
**Pull request by ThibaultFy**
## Companion PRs

- https://github.com/Substra/substra-tools/pull/85 (main)
- https://github.com/Substra/substrafl/pull/169
- https://github.com/Substra/substra/pull/388
- https://github.com/Substra/substra-tests/pull/283
- https://github.com/Substra/substra-documentation/pull/367
- https://github.com/owkin/substra-ci/pull/127
- https://github.com/owkin/substra-generator/pull/136
closes FL-979

### CODE REVIEW

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11 --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11 --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11 --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11 --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11 --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11 --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11 --benchmarks mnist

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11 --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
GKE 1.27

/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11 --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11 --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by SdgJlbl — APPROVED** [review]

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11 --benchmarks mnist,camelyon

**Comment by ThibaultFy** [comment]
/e2e --tests sdk,substrafl,doc --mode standalone --refs substra=python-3-11,substra-tests=python-3-11,substra-ci=python-3-11,substra-documentation=python-3-11 --benchmarks mnist,camelyon

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
